### ISSUE TITLE
Esimene kasutamiskõlbulik versioon

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#101]
Kui #100 saab korda siis võiks nagu käima lükata asja.

Hea meelega tahaks Tartus homsest katsetama hakata. Teeks esimesed aruanded juba uue süsteemiga, esimese nädala näiteks kassa-test keskkonnas. Selle jaoks tuleks aga paar väikest asja teha:

* #100 mergeda
* Tartu andmed üle tuua (hakkan nüüd tegema)
* Liigutada /fe/ pealt root kataloogi. Sellega seoses saab _service workeri_ uuesti käima lasta ning staatiliste failide andmemaht väheneb vähemalt 90%.
* Sessiooni meeles pidamine. Minu tehnoloogia valiku tõttu on brauseri poolne parooli salvestamine raskendatud ning kasutaja mugavust silmas pidades on väga vajalik, et sama seadme peal ei peaks kogu aeg sisse logima ja parooli trükkima.
* kassa-test keskkonda üles laadida

**Comment by tanelk** [comment]
Ülekanded ja saldod on üle toodud. Ostud ootavad hetkel andmebaasi migra taga (lives on veel pos_id sees)

**Comment by tanelk** [comment]
Nüüd ongi vaid #100 mergemine jäänud. Oleme valmis selleks?

**Comment by zebraf1** [comment]
Mergetud
