### ISSUE TITLE
Toodete järjekord aruande koostamisel

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#103]
Kasutajale on mugavam, kui aruande koostamisel on tooted sorteeritud gruppi järgi. 
Praegu on nime järgi.

**Comment by zebraf1** [comment]
Toodetel saab järjekorda määrata, selle järgi olid need vanas aruandes sorteeritud

**Comment by tanelk** [comment]
Toote järjekord polegi otseselt oluline. 
Tähtsam oli, et ühe tootegrupi asjad tuleks järjest, mis sai praegu ka tehtud.
