### ISSUE TITLE
Ostukorvis toote kogus 0

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#105]
Ostes saab määrata toote koguseks 0 ning see läheb läbi ja pärast ilmub ostude alla (vt Tallinna konvendi ostud).
Negatiivset kogust server keelab, sinna kontrolli võiks lisada siis ka 0.

Viga pole minu leitud vaid valves olnud testijal hakkas igav :) .

**Comment by zebraf1** [comment]
Panin Reports branchi selle fixi
