### ISSUE TITLE
Aruande puudujäägi arvutamine

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#109]
Peab üle vaatama, kuidas seda arvutatakse. Kui toote hinda muuta, siis kasutajaliideses arvutatud ja backendis arvutatud on erinevad.

**Comment by zebraf1** [comment]
Aruande iga rea külge salvestatakse ka toote praegune hind ning aruande kuvamisel kuvatakse selle toote hind kui see erineb praegusest hinnast. Nii oli vanas

**Comment by zebraf1** [comment]
GET reports tagastab reportid, selle küljes on reportRows ja iga row küljes on currentPrice. Kui hind muutub pärast aruande tegemist, siis need puudujäägid arvutatakse ikkagi aruande hetke hindade järgi.

**Comment by tanelk** [comment]
Olen täitsa teadlik, kuidas seda arvutatakse. Kasutajaliideses oli praeguse ja eelmise aruande hinnad omavahel segatud ning seetõttu tuli sealt erinevus.

**Comment by zebraf1** [comment]
Läks üles testi
