### ISSUE TITLE
Müügipunkti sooritatud ostude voog

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#110]
Sooviti järgmist võimalust:

Konvendi köögis oleval arvuti ekraanil võiksid joosta nt viimase 15min jooksul tehtud ostud. 
Tekkis olukordi, kus unustati maksta ning sinna vaadates saaks kähku kinnitust, et kas ikka maksti.

**Comment by zebraf1** [comment]
Kas konvendi köögi arvuti võiks teha müügipunktiks? Müügipunktil oli eraldi vaade tehtud, kus kuvatigi viimaseid tehinguid ja ostmise lehte. Anonüümset ostmist ei ole hetkel? Seda saaks ainult sularahaga teha

**Comment by tanelk** [comment]
Hakkasin seda tegema, müügipunktiga seoses tuli üks viga välja:

Ostu sooritades ignoreeritakse kaasa pandud konvendi id väärtust ja salvestatakse ost müügipunkti konvendi alla.
Sellist olukorda ei tohiks tekkida, kus Tartu arvutist tahan Tallinnasse ostu teha aga katsetades tuli välja. Siiski praegune käitumine on päris halb. Pigem eelistaks, seda, et kui kaasa pandud konvendi id ei klapi müügipunktiga, siis anda veateade vastu ja ostu ei salvestata.

**Comment by zebraf1** [comment]
Jah, see case on tõesti võimalik, aga tavaolukorras ei tohiks seda ju juhtuda.
a) Brauser on määratud müügipunktiks mingile konvendile näiteks Tartu - st peaks asuma füüsiliselt ka Tartus
b) Kasutaja peab selles müügipunktis olema sisse logitud - asuma samuti Tartus, selle arvuti juures
c) Valima konvendiks Tallinn ja tegema ostu - mis on ebaloogiline, et ta Tartus olles Tallinnast ostab

Ainuke case, et ta ostab kellelegi, kes on Tallinnas (teeb välja).

Lisasin piirangu, et API annaks veateate:
"See brauser on määratud müügipunktiks (Tartu) ja ei luba valitud konvendist ostu"

**Comment by tanelk** [comment]
Peamine probleem minu jaoks oli see, et testides tulid mingid "anomaaliad" sisse :) .

**Comment by zebraf1** [comment]
Ok, kas nüüd on parem?

**Comment by tanelk** [comment]
Jah, suurepärane
