### ISSUE TITLE
Andmete lehekülgedeks jagamine

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#113]
Praegune andmete kuvamiseks kasutatav tabel ei toeta "mugavalt" _pagination_-it ning seetõttu pole seda ka siiani kasutanud.
Kuna aga osades valikutes tekib juba 7 päeva jooksul päris suur hulk ridu (konvendi ostud nt), siis on rakenduse kasutamine telefonis kohati uimane. Tuleb jagada paarikümne realisteks lehekülgedeks.

API peaks enamuses toetama _limit_ ja _offset_ argumente, tuleb üle kontrollida.

**Comment by tanelk** [comment]
Maru vahva oleks kui GET päringutega tuleks kaasa ka filtritele (va _limit_ ja _offset_) vastavate andmete kogus, sellega saaks kasutajaliideses kuvada lehekülgede arvu jms.

**Comment by tanelk** [comment]
Tundub, et _content range header_ on üks meetodeid selle info edastamiseks:
http://otac0n.com/blog/2012/11/21/range-header-i-choose-you.html

**Comment by zebraf1** [comment]
Tavaliselt olen limit ja offset parameetrid controlleris lisanud otse query builderisse kui antud.
->limit()
->offset()
