### ISSUE TITLE
Majandusaruanne/väljavõte

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#115]
Majanduse eestseisjale on väga oluliseks infoks kassa kasumlikkus. Praegustest aruannetest/inventuuridest seda välja ei tule.

Tahaks näha toodete müügitulu ning ka kogu kassa müügitulu suvalise ajavahemiku jaoks.
Majanduse eestseisja valib ajavahemiku ning selle pealt arvutatakse iga toote kogused alguses nii kassas kui ka laos. Kokkuvõtvalt kujutatakse toodete liikumisi (lattu, kassasse, müüdud) ning ka puudujääke aruannetest ning lõppseise.

Asja teeb huvitavaks see, et toote sisseostu hind kõigub ajas. Märksõnaks selle lahendamiseks on FIFO.

Kõik vajalik info on andmebaasis juba olemas, nüüd vaja vaid see välja tuua sealt.

**Comment by zebraf1** [comment]
Mulle paistab, et see on lives. Panen kinni
