### ISSUE TITLE
Lõputud/aruande välised tooted

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#116]
Probleem:
ÕKassa rakendust tahetakse kasutada "toodete" jaoks, mis ei mahu meie lihtsasse mudelisse. 
Konvendis ööbimine ning saunarätikute laenutamine on "piiramatud" ressursid, mida pole tarvis aruandeid tehes kokku lugeda.

Lahendus:
Lisada toodetele boolean väli "aruandluses" (võib konventide kaupa erineda).  Kõigil olemasolevatel toodetel on see väli True.

Mis on erinevat toodetel, millel on see väärtus False:
Valvearuande koostamisel seda ei pea lugema (laoseisu, kui sellist ei jälgita)
ME tarnete all seda toodet ei ole. 
Aruanded vaadates seda toodet ei ole. (Kui jõuda #115 -ni, siis sealt näeb)
Toodete all on võimalik seda toodet näha ja muuta. (kogused puuduvad)

**Comment by zebraf1** [comment]
Kas midagi oli veel seal teha? Praeguse seisuga probleeme silma ei hakanud

**Comment by tanelk** [comment]
Nihutasin natuke veel piksleid, muidu korras.
