### ISSUE TITLE
Majanduseestseisja saab piirata krediidilimiiti

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#47]
Lisada seadete leht, kus saaks hallata majanduseestseisja süsteemiparameetreid

Esimese asjana võiks saada sealt hallata krediidilimiiti, millest alla ei saa tehinguga minna.

Lisada ollekassa_settings tabel.
Kontrollida krediidimakse tegemisel, kas krediidilimiit läheks lõhki ostu sooritamisel ning anda vastav veateade.

**Comment by tanelk** [comment]
See võiks olla praegu kõige kõrema prioriteediga töö.

**Comment by tanelk** [comment]
Rääkisin majanduse eestseisjaga ning see asi tuleb ikkagi ka veel enne _launchi_ ära teha. Võla numbrid võivad muidu väga kergelt kasvada. Ning lisaks võiks saada määrata kolm eraldi limiiti - musmajala, tegevliikmetele ja vilistlastele.

**Comment by zebraf1** [comment]
Ok, võtan see nädal töösse. Võib esmalt kiire variandina need limiidid otse sisse kirjutada ja pärast hallatavaks teha.

**Comment by zebraf1** [comment]
Teen UI jaoks eraldi kande
