### ISSUE TITLE
Laoseisu salvestamine

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#58]
Tekitada uus andmebaasi tabel product_inventory, kus saab hoida laoseise: convent_id, product_id, storage_type ('STORAGE', 'WAREHOUSE'), amount.

Teha API päringud laoseisu küsimiseks ja settimiseks (GET ja PUT)
Filtrid: conventId, storageType, productId või active

**Comment by tanelk** [comment]
Otse läbi API toodete koguse muutmine ei pruugi olla kõige parem variant. Mina pigem seoks suurused nagu toodete kogused ja nt ka kasutaja saldo teiste tegevustega.

Toote kogust muutvad tegevused:

- tarned (toote sisse toomine väljapolt)
- Liigutamised STORAGE ja WAREHOUSE vahel
- ostud
- aruanded (kui kogus erineb sellest, mis peaks olema)

Saldot muutvad tegevused:

- ostud
- ülekanded

Selline mudel oleks märksa läbipaistvam, kui otse PUT meetodiga muutmine, ning iga tegevuse juurde jääb ka märk kasutajast.

**Comment by zebraf1** [comment]
Hea tähelepanek. Ma paningi siia esimesed mõtted kirja. Mõte oli, et aruande salvestamisel salvestatakse need ära, aga ilmselt see peaks jah taustal toimuma, mitte otse. Seda laoseisu tabelit on ikka vaja.

**Comment by zebraf1** [comment]
Lisasin hoopis 2 välja juurde product_info tabelisse: storage_amount ja warehouse_amount.
Lisasin product väljundisse inventoryAmounts, mis võib olla null või dictionary(warehouse, storage)

**Comment by zebraf1** [comment]
migra käivitamiseks lokaalselt tuleb lasta käima: "php app/console propel:mig:mig"
mudelite uuendamiseks vaja lasta käima: "php app/console propel:model:build"
