### ISSUE TITLE
Lisada FrontendBundle

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#59]
Tanelile bundle, mis renderdab index.html

**Comment by tanelk** [comment]
Kindlasti võiks olla kaks eraldi kaustad src ja build (nimed pole olulised), ühte siis ilus lähtekood ja teise siis build scripti poolt tehtud.

**Comment by zebraf1** [comment]
Võid vaadata selle commiti sisu, ma lisan sinna kommentaarid

**Comment by zebraf1** [comment]
@tanelk võid omapoolsed kommentaarid ka lisada selle commiti sisse

**Comment by zebraf1** [comment]
Tundub, et sai vähemalt pildi ette. Panen selle kande kinni
