### ISSUE TITLE
Frontendi ühildamine süsteemiga

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#60]
Esimene commit on tehtud ja pm asi võiks töötada. 

Serveris peaks olema installeeritud npm ning käivitama käsud "npm install" ja "npm run build". See teeb kõik FE seonduva ära.

Nüüd aga väiksed murekohad.
index.html fail on pm dubleeritud kahes kohas. Üks neist on .twig template ning teist kasutab _build script_ FE struktuuri tuvastamiseks. Oleks võimalus .twigis lihtsalt teha static import aga siis ei pruugi _assetite_ asukohad paika jääda. 
Et kasutada _service worker_ -eid peab fail service-worker.js asuma root kaustas (mitte serveri aga kliendi jaoks, ning /fe sobib, kuna kõik talle oluline on "madalamal"). Siin vist aitaks, kui see viia kausta views ja lasta läbi template generaatori aga iga kord kui jooksutada käsk "npm run build" genereeritakse see fail uuesti (sisaldab kõigi FE failide hashe, et neid korrektsel kliendi pool cacheda).

Muidu tundub korras

**Comment by tanelk** [comment]
Kuna _build scripti_ jaoks vaja minev fail võib olla vägagi minimaalne, siis sai see probleem aa53d6a7fd702936daf6a43c3ba8dc9aec4d0d9e -ga ära parandatud.

**Comment by zebraf1** [comment]
Ok, kas hetkel said selle twig mure lahendatud või on mingi probleem üleval veel?
