### ISSUE TITLE
Kassade haldus

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#61]
Luua kassade vaade, mida näeb admin (enda konvendi asju) ja super admin (kõikide)

Vaata api/doc PointOfSales päringuid. Seotud kanne #49 (list ja view osa tehtud antud hetkel)

**Comment by tanelk** [comment]
API annab name väljale väärtuseks device_info.
`{
  "status": "success",
  "data": {
    "pointOfSales": [
      {
        "id": 2,
        "name": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.85 Safari/537.36",
        "conventId": 6,
        "createdAt": "2016-08-13 15:06:54",
        "createdBy": "Tanel Kiis"
      }
    ]
  }
}`

**Comment by zebraf1** [comment]
Parandasin ära

**Comment by zebraf1** [comment]
Lisatud POST, PATCH ja DELETE meetodid pointOfSale endpointile.
