### ISSUE TITLE
Aruannete kuvamine

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#66]
GET /reports/ päringust tulevad aruanded. Filtreerida saab ajavahemiku järgi, konvendi järgi (super admin).
- Aruandeid peab olema võimalik vaadata tagantjärele
- Aruandeid saab filtreerida ajavahemiku järgi
- Aruande avamisel kuvada tooteid, nende kogust ja tolleaegset hinda
- Admin saab enda konvendi aruandeid muuta, super admin saab kõiki aruandeid muuta
- Tavakasutaja saab muuta enda loodud aruandeid
- Iga sisseloginud kasutaja saab sisestada uut aruannet (POST reports)
- Aruandesse peaks saama lisada kõiki aktiivseid tooteid
- Aruande muutmisel tuleks kasutada massiivi elementidel numbrit (ilmselt tuleks sinna panna productId, peab API pool natuke ringi tegema) - muidu tekivad topelt kirjed. "Report[reportRows][0][amount] ja Report[reportRows][0][productId]" on hetkel

**Comment by zebraf1** [comment]
Ma hetkel pärast salvestamist seda loodud reporti kaasa ei anna, millegipärast oli siis päring 10 sekundit. Kui pärast salvestamist eraldi pärida, siis oli normaalse kiirusega. Vajadusel võin debugida seda, aga kui on ok, siis ma ei hakka.

**Comment by tanelk** [comment]
Aruande tegemisel tahaks ligi pääseda järgnevatele suurustele:
Palju oli toodet kapis eelmise aruande lõpus (seda saab kätte)
Palju on toodet ostetud 
Palju on ME lisanud toodet kappi juurde
Nende põhjal saan arvutada eeldatava koguse kapis

Neid kasutajale kuvades aruande tegemisel on märksa parem ülevaade ja ka kohe arusaamine, kust võiks puudujääk/ülejääk tulla.

**Comment by zebraf1** [comment]
Kuidas sa seda mõelnud olid?

Mul oli mõte, et toote küljes on kirjas need kogused laoseisu ja kapiseisu kohta. 
Kui keegi ostab toodet, siis kapi seis muutub vähemaks.
Hetkel on meil eraldi majanduseestseisja aruanne (toodete lisamine kappi ja raha kassast välja) - selle tulemusena lisataks kapiseisule numbrid juurde (vaja teha).
Ilmselt tuleks ka mingi variant teha, kus saab laost kappi liigutada tooteid.

Minuarust suur küsimus on siin see, et kas inventuuri aruande tegemisel kirjutatakse kapiseisud üle või peab seda majanduseestseisja tegema kui ta on üle vaadanud. Aruande tegijad eksivad aeg-ajalt, kuidas seda probleemi lahendada? (vajab ka tegemist APIs)

Ilmselt on sul vaja teha toodete päring, sealt saad sa tooted - nimed ja laoseisud. Kõik aruandes olevad tooted tuleks välja kuvada - kui currentPrice ei ole product.price, siis mul kuvatakse välja ka, et hind on muutunud. Uue aruande lisamisel tuleks välja ainult aktiivsed tooted.

Aruandele ma lisasin külge juba ka need eeldatud ja tegelikud rahalised väärtused (ideaalis peaks need klappima). Samuti lisasin valves olevate liikmete nimed. Need asjad olid meil süsteemis juba olemas. Intranetis valvete lehel tegin ka nähtavaks, kellel on valve jäänud tegemata (Tallinna konvendil ainult hetkel)

**Comment by zebraf1** [comment]
Tegin testi, kus panin reportRows elementide ID'deks product ID'd ning kõik toimis ilusti.

Pane ka nii post parameetrid kaasa:
```php
[
    'Report' => [
        'cash' => '12.34',
        'reportRows' => [
            12 => [
                'amount' => 22,
                'productId' => 12
            ]
        ]
    ]
]

**Comment by tanelk** [comment]
Need võiks tõesti olla iga tootega kaasas. 

Ma arvan küll, et kogused peaks iga aruandega muutuma. Ei saa eeldada, et ME käiks igapäevaselt aruandeid üle vaatamas.

**Comment by zebraf1** [comment]
Võib-olla selline variant, et kui maj. eestseisja aruannet lisada, siis saab valida kuhu tooted pandi ja kust tooted võeti.
Näiteks oleks mingi dropdown: Väljast lattu, väljast kappi, laost kappi

**Comment by zebraf1** [comment]
Products päringust tulevad toodetel need laoseisud kaasa muidu juba ju:
```php
        "inventoryAmounts": {
          "warehouse": 0,
          "storage": 0
        }

**Comment by tanelk** [comment]
Ning saan ma õigesti aru, et liigutatavad kogused tulevad siis nendest UPDATE tüüpi aruannetest, kui #69 valmis saab? 

Ehk siis viimasest VERIFICATION tüüpi aruandest saab viimase aruande seisu. Toodetega käivad kaasas eeldatavad hetkeseisud (võtavad arvesse oste ja lisamisi) ning UPDATE tüüpi aruandest saab välja lugeda, kui palju on koguseid (raha kui ka tooted ) muudetud ME poolt? 

Kuna kõige viimane antud tüüpi aruanne konvendi kohta on üsna tihti kasutatav, siis vb oleks hea, kui saab ka teatava shortcuti nende kätte saamiseks. Hetkel peaks pärima kõik aruanded iga kord (ei tea ju kunas see tehti) ja siis sealt viimase välja filtreerima.

**Comment by zebraf1** [comment]
Õigesti jah, VERIFICATION aruanded on valvete poolt lisatud ja kajastavad kassa seisu (kapis tooted ja kassas sularaha). UPDATE aruanded on ME poolt lisatud - sularaha väljavõtmised ja toodete lisaimine (liigutamine). Tulevikus võib sellise aruande teha ka muu ametnik (ROLE_SUPPLIER), kes tarnib kassasse tooteid (käsitöö õlut vms) ja võtab kassast raha (sama tegelinski või tantsukursuste korraldaja Tlns näiteks).

Vaatab mis saab teha, et oleks lihtsam pärida viimast aruannet, hetkel jah hästi ei saa.

**Comment by zebraf1** [comment]
settings päringu vastusest tuleb nüüd iga konvendi currentCash ka, mida uuendatakse raporti salvestamisel ja sulatehingute tegemisel.
Teen laoseisude salvestamise ka samamoodi ära peagi.

**Comment by zebraf1** [comment]
Lisasin vajalikud filtrid, et saaksid viimase aruande kätte.

Pane report päringule kaasa limit 1 ja reportType='VERIFICATION'. Siis saad viimase valve lisatud aruande kätte. Kui type ei pane, siis tuleb üldse viimane.

**Comment by zebraf1** [comment]
UPDATE tüüpi aruandeid ei luba hetkel muuta, ainult verification omasid. Kui on probleem, siis tuleb uus korrigeeriv aruanne lisada.

#66 sai ka tehtud, nüüd salvestab aruande muutmisel ka toodete kogused ära.
UPDATE aruande lisamisel saab kaasa anda inventorySource ja inventoryTarget (null, 'storage' või 'warehouse').
Vaikimisi on source null (ei võeta kuskilt maha). Vaikimisi on target 'storage' (lisatakse käibele).
sourcest eemaldatakse ja targetile lisatakse kogused.
VERIFICATION puhul need parameetrid rolli ei mängi - pannakse alati sisestatud väärtused laoseisuks (storage).

**Comment by tanelk** [comment]
> settings päringu vastusest tuleb nüüd iga konvendi currentCash ka, mida uuendatakse raporti salvestamisel ja sulatehingute tegemisel.

Tundub, et seda ei ole ikkagi lisatud.

GET /api/settings/?_format=json
Response:
{
  "status": "success",
  "data": {
    "activeConvents": [
      {
        "id": 1,
        "name": "Tartu",
        "settings": {}
      },
      {
        "id": 2,
        "name": "Tallinn",
        "settings": {}
      }
    ]
  }
}

**Comment by tanelk** [comment]
#80 raames tegemisel
