### ISSUE TITLE
Ostmise UI

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#68]
UI pool on ostmise osa juba enam-vähem tehtud, aga lõpuni ei toimi.
#67 käigus sai lisatud API doc (Purchase) ostude jaoks.

Potentsiaalsed kasutuslood
- Kasutaja on sisse loginud ja tahab osta oma konvendist toodet 
  - krediidiga - rebased, tegevliikmed, mõned vilistlased
  - sulas - rebased külalistele, teised? pigem vist kasutatakse sel juhul müügipunkti kassat
  - lisada krediiti pannes kassasse sularaha - krediidiga maksvad liikmed
- Kasutaja on sisse loginud ja tahab osta võõrast konvendist toodet sularahas - nt Tallinna liige Tartus (sel juhul peaks saama vahetada konvendi vaadet ostulehel) Kas on mõtet teha?
- Kasutaja ei ole sisse loginud ja tahab osta oma/võõrast konvendist toodet sularahas - kõik tegelased konvendis paiknevast müügipunktist (eelkõige vanemad vilistlased, külaliste joogid jne) - eeldab statsionaarset kassat, triipkoodilugeja oleks tore.
- Kasutaja ei ole sisse loginud ja tahab osta oma konvendist toodet krediidiga - vajab username/password ajutiseks. Tartus ma saan aru, et sai lihtsalt valida, kelle nimel osta - need erisused tuleb ka veel lahendada meil. Liikmed, kel sularaha pole kaasas (unustas või mugavam)

**Comment by tanelk** [comment]
Iga ostuga peaks käima kaasas tasuja (member id, vaikimisi sisse logitud kasutaja) ning ka konvendi id, kus ost sooritatakse (ei pruugi olla kasutaja "kodukonvent"). Praegune API seda ei võimalda. 

Teiseks oleks juurde vaja GET members päringut, seal oleks vaja ainult id ja nimi. 

Konvendi vaadet saab vahetada vajutades mustal taustal konvendi nimele.

**Comment by zebraf1** [comment]
#72 - liikmete otsingu kanne tehtud

**Comment by zebraf1** [comment]
#73 - teise nimel ostmise kanne tehtud

Kui ostad võõrast konvendist, kas siis saab ka krediidiga maksta? Kas sel juhul peaks olema kasutaja krediit konvendipõhine ning mõlema konvendi krediit kuvatud? Konvendid majandavad ju eraldi.

**Comment by tanelk** [comment]
Mina teeks nii, et krediit ei oleks konvendipõhine ja nt igakuiselt genereeritakse ME-dele "aruanne", kus on siis näha palju on "võõrastes" konventides makstud ja siis selle põhjal tehakse tasaarveldust. Need summad peaks tulema piisavalt väiksed ühe kuu lõikes, et see puudujääk ei tohiks anda tugevalt tunda konvendi rahanduses.

See arvepidamine ei ole küll niisam lihtne. 
Peab arvestama sellega, et inimene ei pruugi teha ülekannet oma kodukonventi. 

Proovisin paberi peal erinevaid skeeme kritseldada ning pakuks välja sellise meetodi:

Peidetult hoida kasutajatel konvendipõhist krediiti, kuid väljapoole kuvada alati siis kasutaja kohta summat üle kõigi konventide. Ostudga siis võetakse krediiti maha vastava konvedi alt. Igakuise aruande käigus tõstetakse kõigil liigmetel krediit niimoodi ümer, et kodukonvendist erinevates kohtades viime krediidi nulli. Need ümbertõstmised liidame konvendi kohta kokku ja tulemus on siis palju selles konvendis on "võõrast raha" kulutatud ja nende põhal saab siis tasaarveldust teha.

Tegin väikese [tabeli](https://docs.google.com/spreadsheets/d/1JI0VIqholI1NSbtRzXvRDcIgFvRFEzMuewIA3lEPQQI/edit?usp=sharing), et natuke mõtet illustreerida.

**Comment by tanelk** [comment]
Valmis
