### ISSUE TITLE
Tehingud API

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#70]
Tehingute jaoks on rest päringud olemas minuarust.
Tuleb lisada API doc
Routing viia API bundlesse
Tehingud teha kovendipõhiseks - #24 - salvestada conventId ja võimaldada filtreerida
Enda tehinguid peaks saama näha konventideüleselt

Vajalik tehingute kuvamiseks (UI kanne vaja teha)

**Comment by zebraf1** [comment]
Tehingud on juba tehtud konvendipõhiseks Taneli poolt.

**Comment by zebraf1** [comment]
@tanelk - kas see purchases asi juba lahendas selle vajaduse ära? Või on vaja ikka tuua transactions päringud ka üle?

**Comment by tanelk** [comment]
Ostud ja ülekanded peaks korras olema. #79 vajab veel lahendamist, ehk saaksid sellega tegeleda. Homme pärastlõunal saan Tartu MEga kokku ning proovime süsteemi erinevate seadmete peal (linux/win/apple/..) ja proovin üldist tagasisidet koguda.
