### ISSUE TITLE
Amount vs count

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#74]
Tootega on seotud amount - see on ühe tooteühiku massiline/ruumiline kogus (100g, 0.5l või 1tk). See on indikatiivne ning ainult kasutajale informatsiooniks.
Ostmise ja tehingutega on seotud count - see on mitu tooteühikut on ostetud (mitu korda peab maksma). Hinnad on alati tooteühikupõhised, mitte kaalu järgi.

Igal pool, kus (product)count asemel on kasutusel termin (product)amount tuleb see ära asendada.

**Comment by tanelk** [comment]
Branchis amount_vs_count on nüüd muudatused tehtud andmebaasi, uute UI-sse ning sellega seotud controllerites ja testides. Saaksid sa vana UI üle käia, tead seda kindlasti märksa paremini.

**Comment by zebraf1** [comment]
Ok, kuule kui sa commitid midagi, siis pane algusesse selle issue number, millega see seotud on. Siis ilmuvad siia kande juurde need commitid.
Näiteks "#74 Changed usages of count" või midagi sellist.

**Comment by zebraf1** [comment]
Mergetud #94
