### ISSUE TITLE
Ostmisel ei peaks sõltuma konvendi id kasutajast

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#75]
Praeguses koodis, kui ei ole tegemist _point of sale_-ga, siis võetakse ostu konvendiks kasutaja kodukonvent - [kood](https://github.com/zebraf1/Kassa/blob/370abecedd7c6c5d463eb785b8f67f6feeb90c21/src/Rotalia/InventoryBundle/Controller/PurchaseController.php#L143).

Kui mina, tartlasena, ostan Tallinnast, siis peaks ostu kohaks ikkagi minema Tallinn (raha sinna ja toote kogused vähenevad). Ehk siis see parameeter peaks päringust tulema.

**Comment by zebraf1** [comment]
Jah, võib selle parameetri lisada. Ma ei ütleks, et see bug on, pigem arendus?

Kas use case on siis see, et Tartu kasutaja on sisse loginud aga paikneb Tallinnas ja tahab osta õlut?

Kuidas kasutaja annab rakendusele teada, et ta on nüüd Tallinnas. Kas kuskil on mingi dropdown, kust saab aktiivset konventi valida? Kõik tooted ja aruanded peaks ka siis Tallinna omad tulema ilmselt, seega mingi üldine valik. Või on see valik ainult ostmise lehel? Kas see on ajutine või vaja baasi ka salvestada kui muudetakse?

**Comment by tanelk** [comment]
jah, usecase on täpselt see.

See asukoha valik on UIs sees ning on üldine, mitte ainult ostmise lehel. Mina seda baasi ei topiks, saab UI pool seda hoida alles.

**Comment by zebraf1** [comment]
Lisatud conventId parameeter payment päringule.
Kui on PoS brauser, siis kasutab ikkagi selle convent ID.
Kui conventId ei anna, siis kasutab kasutaja kodukonventi.

Tee omalt poolt siis arendus, et see valitud konvendi ID kaasa panna.

**Comment by tanelk** [comment]
Kui #76 ja #74 korda saavad siis tuleb veel väike muudatus sisse aga muidu tundub korras olevat peale 39fda7d57fc23c072c9313fadec3f09cdd045301-i.
