### ISSUE TITLE
Veateated ei järgi ühtset struktuuri

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#76]
Näide kolme erineva päringu veateatest:

POST /api/authentication/
{
  "status": "fail",
  "data": "Login token puudub"
}

PATCH /api/pointofsales/
{
  "status": "fail",
  "data": {
    "message": "Müügipunkti ei leitud"
  }
}

POST /api/purchase/
{
  "status": "error",
  "message": "Ostukorvis on vigane toode: {\"id\":\"1\",\"amount\":\"1\"}"
}

Pööraks just tähelepanu sellele, et veateade on kolme erineva koha peal, kas siin on mingi loogika (erinevat tüüpi vead vms) või lihtsalt näpuviga?

**Comment by zebraf1** [comment]
Süsteem on olemas jah, aga see on ilmselt liiga keeruline, tuleks lihtsustada.
status = success, fail, error
fail (kliendi viga) peaks olema kui postitatud parameetrites on viga ja siis data seest peaks saama iga ette antud parameetri kohta vea teate. "Müügipunkti ei leitud" on kahtlane case, kus message on data sees. message asemel peaks olema see ID vist.
error on serveri poolne viga ja seal data pole, ainult message.

**Comment by tanelk** [comment]
Kui juba fail annab ainult ühte moodi ja _error_ annab ainult teist moodi, siis oleks minu poolt täiesti OK, kuid kolme erinevat varianti on natuke tüütu _parseda_.

**Comment by zebraf1** [comment]
Teeks nii ümber, et message võib alati tulla ja siis see on kasutajale kuvatav teade  (popup või mingi notification riba all vms).
Kui tuleb data ka, siis see on mingi vormi submittimise viga ja seal on siis vormi elementide nimed data sees ning iga kohta oma veateade.
"error" siis on serveripoolne viga ja "fail" on sisendandmete viga - ma ei tea kas seda on vaja eristada üldse, vist peaks http koodid tulema õigesti (4xx ja 5xx) ja selle järgi saab aru. Jätaks siis ainult "error"

**Comment by zebraf1** [comment]
Vaatasin siin on häid näited: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#http-status

HTTP code järgi saab teada, kas oli viga (>=400) või success (<400)

Üldised veateated
```
{
  "code" : 1234,
  "message" : "Something bad happened :(",
  "description" : "More details about the error here"
}
```

POST, PUT, PATCH puhul validatsiooni vead:
```
{
  "code" : 1024,
  "message" : "Validation Failed",
  "errors" : [
    {
      "code" : 5432,
      "field" : "first_name",
      "message" : "First name cannot have fancy characters"
    },
    {
       "code" : 5622,
       "field" : "password",
       "message" : "Password cannot be blank"
    }
  ]
}
```

**Comment by zebraf1** [comment]
Hüppa branchi otsa fail_response_structure_change ja vaata, kas UI poolt on korras või vaja ka midagi fixida?
Kui status=fail, siis veatede on nüüd messages sees (samamoodi nagu status=error puhul). Kui on vormi vead, siis data sees on otse need errorid, mitte eraldi errors muutuja sees.

Vaata koodi muudatused üle, mis controllerites ja päringutes need veateated said muudetud.

**Comment by tanelk** [comment]
Põgusal vaatlusesl tundub, et praegu asjad toimivad! 

Tundub, et kohati on veateated inglise keeles:

{"status":"fail","data":{"ProductType":"This value should not be blank.","name":"This value should not be blank.","price":"This value should not be blank."},"message":"Toote salvestamine eba\u00f5nnestus"}

Koodi vaadates jäi mulje, et need on Symfony sisemiste kontrollide tulemused ning kas on võimalik kuskile lisada tõlkefail nende üksikute veateadete jaoks? Tühi väli on arvatavasti peamine vea, UI kaudu ei suutnud muid ette manada. 

Teiste kohtade peal on ilusti eesti keelne:

{
  "status": "fail",
  "data": {
   "type": "Vigane raporti tüüp"
  },
  "message": "Vigased parameetrid"
}

**Comment by zebraf1** [comment]
Hmm, ilmselt sisemine keel on inglise jäänud, tuleb panna eesti.

**Comment by zebraf1** [comment]
app/config/parameters.yml failis on locale. See peab olema et. Rotalia live ja test confis oli see en, ma muutsin ära et peale. Võid omal lokaalselt ka üle vaadata.
