### ISSUE TITLE
Ostmisel ei leita toote hinda

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#77]
POST /api/purchase/ 
Toote valideerimine ($this->validateBasketItem($item)) ebaõnnestub, kuna tootel ei ole hinda kaasas, see peaks tulema andmebaasist, mitte päringuga.

dev.log:
[2017-08-02 07:11:34] app.WARNING: Invalid price for basket item: {"id":"3","amount":"1"} [] []

**Comment by zebraf1** [comment]
Hmm, kas sellisel juhul ei anta päringu vastusest õige hind? Ma mäletan, et ma tahtsin nii teha, et kui kasutaja lisab ostukorvi ühe hinnaga ja ostmise hetkel on hind muutunud, siis tuleks kasutajale info selle muutumise kohta. Samuti kui toode ei ole enam saadaval.

Ma ei mäleta kas sul üldse ostukorvi funktsionaalsus on, või saab ainult 1 kaupa osta? 1 kaupa ostmise puhul jah ei oleks vaja, selle tarbeks võib uue requesti teha.

**Comment by tanelk** [comment]
Okey, nüüd on use case arusaadav. /api/doc pole hinda sees, võiks lisada.
Ostukorv on olemas, ei pea ühe kaupa ostma

**Comment by zebraf1** [comment]
Lisasin API docis selle price muutuja. Kui muud pole vaja teha, siis panen kinni.
