### ISSUE TITLE
Müügipunkti kustutamine

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#78]
DELETE /api/pointofsales/2 annab veateate:
{
  "status": "error",
  "message": "Unhandled exception: Unable to execute DELETE statement [DELETE FROM `ollekassa_point_of_sale` WHERE ollekassa_point_of_sale.id=:p1] [wrapped: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`symfony`.`ollekassa_transaction`, CONSTRAINT `transaction_pos_fk` FOREIGN KEY (`pos_id`) REFERENCES `ollekassa_point_of_sale` (`id`))]"
}
Foreign key constraint keelab kustutamist, ehk peaks panema juurde boolean lahtri, mis määrab aktiivsuse ning lisama PATCH päringu?

**Comment by zebraf1** [comment]
Aijah. Ilmselt kustutada ei tahaks kui vaja kuvada tehingu juures kassa nime.
Teisalt küsimus, et kas on tarvis seda tehingu külge salvestada millisest kassast see osteti? Ilmselt piisaks, millisest konvendist see on ostetud (convent_id)?

**Comment by tanelk** [comment]
Nõustun, et võib piirduda konvendi idga

**Comment by tanelk** [comment]
Pole müügipunkti, pole probleemi.
