### ISSUE TITLE
Teise nimel ostmine

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#79]
POST /api/purchase/credit/ päring tundub ignoreerivat memberId parameetrit, andmebaasis on tabelis ollekassa_transaction member_id ja created_by väärtused alati samad.

**Comment by tanelk** [comment]
Lisaks puudub ollekassa_transaction tabelist konvendi id (pos_id võib olla NULL).

**Comment by zebraf1** [comment]
Ilmselt siis bugi jah, pean uurima. konvendi ID kohta panin ka kommentaari teises issues #78 
Hetkel oli nii, et kui pos_id oli antud, siis tehtud tehing kassast, vastasel juhul on kasutaja ise teinud tehingu muust brauserist/mobiilist. Siis arvestatud nagu kodukonvendist tehtud. Mõistlik ilmselt oleks alati lisada convent_id ja kaotada pos_id tehingu küljest.

**Comment by zebraf1** [comment]
Aha, mul on koodis juba todo ka #58 raames:
// TODO: remove point_of_sale_id from transaction, use convent_id instead. Solves FK constraint issue

**Comment by tanelk** [comment]
Siin siis on jätkuvalt probleemiks see, et tasuja (member_id) ja ostja (created_by) on alati samad, vaatamata päringule.

**Comment by zebraf1** [comment]
Väike fix tehtud, otse masterisse.
