### ISSUE TITLE
Ostude ülevaade

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#81]
Ostu sooritamine võiks paari bugfixi pärast valmis saada ning siis oleks vaja ka neid oste kuvada:

GET /api/purchase/  (kõik teised endpointid on mitmuses, muudab selle ka ära?)

Usecases:

- Kasutaja näeb enda varasemaid oste, mis on tehtud ükskõik millises konvendis. (kasutaja võib olla nii ostu sooritaja kui ka ostu eest tasuja).
- ME näeb kõiki tema konvendis tehtud oste (sõltumata ostja/tasuja kodukonvendist).
- Super admin saab vaadata kõike oste.

Filtrid:
- member_id: tavakasutaja saab panna ainult enda id, vastasel juhul veateade. Võimekuse koha pealt oleks parem, kui tasujal ning ostjal oleks eraldi filter aga see ei klapi use casedage. Pigem oleks see OR filter. Võib olla ka tühi (ainult adminil).
- convent_id: Võib olla tühi (tava kasutaja vaatab enda kõiki oste, member_id peab olema paigas) või peab kasutajal olema vastava konvendi admini õigused.
- dateFrom, dateUntil - sama mis aruannetel.

Sorteerimine:
Aja järgi uuematest vanemateni.

Tagastatavad väljad:
- id
- ostja
- tasuja
- toote_id
- toote_kogus (count, mitte amount)
- hind sellel hetkel
- konvent_id
- aeg
- ostu tüüp (cash/credit)
- ???

Boonus:
Aruande koostamisel tahan teada, palju on antud konvendis igat toodet ostetud pärast viimast VERIFICATION aruannet. Seda saaks siduda selle päringuga aga ei tundu mõistlik, pigem lisada päringule GET /api/products/ alla eraldi väli selle kohta, niigi on seal juba mõned kogused (laos/müügis). (aruande koostamise UI ootab selle ning #80 taga)

Kõigele sellele on UI põhimõtteliselt olemas, kui endpoint valmis, siis saab selle võrdlemisi kergelt külge pookida.

**Comment by tanelk** [comment]
Kui #83 saab heakskiidu, siis hakkan sellega tegelema.

**Comment by zebraf1** [comment]
#83 on mergetud, mis selle kande seis on?

**Comment by tanelk** [comment]
Tundub korras olevat.
