### ISSUE TITLE
Tootele tootegrupi lisamine annab vea

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#86]
Alates v3.1 Tekkis #82 käigus
Tekib "Vormil esines vigu", aga lahtri juures vea kirjeldus puudub.

**Comment by zebraf1** [comment]
Korras, test keskkonnas testitud

**Comment by zebraf1** [comment]
API kaudu nüüd enam ei tööta productGroupId parameeter POST ja PATCH päringutel

**Comment by tanelk** [comment]
Korras!
