### ISSUE TITLE
Andmebaasi sisestamisel viga 

### ISSUE THREAD

**Issue by tanelk** [zebraf1/Kassa#89]
Vaatan, et sa koristasid natuke minu korraldatud jama ära, kuid sellega kaasnes üks probleem.

> php56 app/console propel:sql:insert --force
```
Use connection named default in dev environment.
[Propel] Exception
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes' in /srv/http/Kassa/vendor/propel/propel1/generator/lib/util/PropelSqlManager.php:232
```

Pika otsimise peale sain lahenduse
```
ALTER TABLE `fos_user` CHANGE `username_canonical` `username_canonical` VARCHAR(191);
ALTER TABLE `fos_user` CHANGE `email_canonical` `email_canonical` VARCHAR(191);
```

Millegi pärast hakkasid need migratsioonidega kaasas käima ja mingites olukordades ebaõnnestuma. Oskad, ehk aidata sellega.

**Comment by zebraf1** [comment]
Hmm, mul viskas ka neid pidevalt sinna genereerimisse sisse. Hetkel mul enam seda häda ei ole.
Ma ise olen upgradenud php 7.1 peale juba, äkki see aitab? Serveris jooksutan ka 7.1

**Comment by zebraf1** [comment]
Miks sa seda force inserti üldse tegid? Seda on vaja siis teha, kui andmebaasi ära kustutad. Üldiselt piisab ainult migratsioonide käivitamisest (propel:mig:mig).

**Comment by tanelk** [comment]
Ma testimise käigus olin kõvasti imelike kirjeid tekitanud ja tahtsin edasi arendamise jaoks puhtalt lehelt alustada. Proovisin ka 7.1-ga, kuid sama error.

Arvaks, et mysql-i versioon on olulisem:
```
tk-arch Kassa$ mysql --version
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for Linux (x86_64) using readline 5.1

```

**Comment by tanelk** [comment]
Pole oluline probleem, muutsin endal jõuga ära ja vaatan edaspidi, et commitidega midagi kaas ei läheks.

**Comment by zebraf1** [comment]
Mul on MySQL 5.6.35

**Comment by zebraf1** [comment]
seda fos_user tabelit me üldse ei kasutagi muide, need võib droppida. Need tekivad iga kord sinna migrasse seetõttu, et see friendsofsymfony/user-bundle omab schema.xml faili, kus on need tabelid kirjeldatud. Me kasutame Rotalia enda liikmed ja users tabeleid.
