### ISSUE TITLE
API päringute analüüs

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#91]
v3.2 release

* sisselogimata kasutajale tehakse authentication päring 2 korda. Tuleks teha 1 kord
* sisselogimisel ei tööta brauseri poolt meeldejätmine, peab iga kord kasutajanime uuesti sisestama (sellepärast, et inputil on autocomplete=off)
* ostmise lehel tehakse members/?limit=0 päring, kust tulevad kõik kasutajad (2195) ja selle response suurus on 145kb ning võtab aega ca 1 sekund. Minu ettepanek oleks seda päringut mitte teha ja vaikimisi kuvada logitud kasutajat nagu praegu (id ja nimi on teada). Kui kasutaja muudab inputi ja vähemalt 1 täht on sisestatud, siis teha see members?name=$name päring. Näiteks members/?name=J päring on 805B ning 63ms.
* Kui minna lehele "Ülekanded", siis tehakse uuesti members?limit=0 päring ja küsitakse uuesti kõik memberid. Kas seda päringut üldse on vaja siin lehel? Nime kirjutamine paistab filtreerivat otse seda tabelit ja ei tehta päringut.
* Välja logimisel tehakse DELETE authentication ja siis jällegi 2 korda järjest GET authentication

**Comment by zebraf1** [comment]
Vaata üle, kas need asjad on võimalik lihtsasti korda saada või mitte

**Comment by tanelk** [comment]
Kui praegused branchid saavad valmis ja mergetud, siis hakkan sellega tegelema.

Paar mõtet:
members päring vajaks lisaks ka hädasti filtrit isActive.
Kõigi päringute puhul peaksime üle vaatama, kus on vaja id-d ja kus on vaja hoopis objekti ennast, javascriptis sql joine teha on natuke liialt raiskav.
Selle parooli meelde jätmisega olen päris pikalt pead vaevanud, tundub, et single page aplicationi puhul on see üldse keerulisem. Vaatan seda autocomplete asja.

**Comment by tanelk** [comment]
Tundub, et see autofill jääb hetkel katki:
https://github.com/PolymerElements/iron-form/issues/197

Oleme oma tehnoloogiate valikutega ajast ees ning peab ootama kunas brauserid järgi jõuavad :).
Ehk saab küpsiste eluiga pikemaks panna? Vähendab seda muret ehk natuke.

Ma subscribesin paarile seotud issule, kui seal mingi muutus on, siis ma vaatan seda edasi.

**Comment by zebraf1** [comment]
Pärast ostu sooritamist esilehel, tehakse uuesti authentication ja setting päringud. Kas see on vajalik?

**Comment by tanelk** [comment]
Kuna ostu sooritamine oli kuni eilseni katki, siis ma igaks juhuks ei usaldanud sealt tagasi tulnud krediidi väärtust ja tegin uue authentication päringu, et krediiti uuendada. Teen selle lähipäevil ümber. Hea et meelde tuletasid

**Comment by tanelk** [comment]
Tekkis probleem sellega, et rakendus on kohati liiga kiire, kui caches on.
Mul on salvestatud link telefoni avalehele ning kuna kõik staatilised failid on caches, siis laeb see üsna kiirelt. Kui vahetult enne avamist lükata internet järgi, siis ei pruugi laadimise hetkeks olla ühendus üleval ja esimesed päringud (GET authentication) ebaõnnestuvad. 
Tuleb interneti ühenduse puudumisel lihtsalt lühikese aja pärast uuesti proovida. Oluline on vaid get päringuid uuesti proovida, muidu võivad näiteks topelt ostud tekkida jms.
